
apikey: ${API_KEY}

jwt:
  secret: q2KLu/ULqHXrNXm2gjwA/vfp+H7KWfe7p2sxCKd0eFhmEXmgPeWyqHcVylLg4N2cH0GNxjtuDfap3PZNJbg1+g==
  expiration: 10000000

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1073148988890-188k39pvbsb7dr0adig03e1hgd96tbts.apps.googleusercontent.com
            client-secret: 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
      profiles:
        include: oauth